name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        mv BasicProject/dotgit BasicProject/.git
        mv ComboProject/dotgit ComboProject/.git
        mv UnitTestProject/dotgit UnitTestProject/.git
        rm -rf .git
        rm -rf .github
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'ProjectTemplates.zip'
    - name: Generate release tag
      id: generate_release_tag
      uses: alexvingg/next-release-tag@v1.0.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: 'v'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "ProjectTemplates.zip"
        tag: ${{ steps.generate_release_tag.outputs.release_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
